Theme
Allgud/music_app pull request #9
Opened 2022-10-09 11:29 UTC by Allgud

Добрый день!

2022-10-10 07:15 UTC, mrerberg requested changes

2022-10-10 07:15 UTC, mrerberg commented on src/components/Layout/Layout.jsx
> +                <Footer />
Футер можешь удалить, так как не используется компонент, он пустой

2022-10-10 07:15 UTC, mrerberg commented on src/components/filter-components/FilterList/FilterList.jsx
> +            ? <FilterByYear theme={theme} buttons={state}/>
Зачем пропсом передавать тему, если можно сразу в компоненте ее и запросить?

2022-10-10 07:15 UTC, mrerberg commented on src/components/filter-components/FilterList/FilterList.jsx
> +                {state.map((el, i) => <FilterListItem key={i} item={el} theme={theme} />)}
https://www.developerway.com/posts/react-key-attribute

2022-10-10 07:15 UTC, mrerberg commented on src/constants/constants.js
> +        title: 'light',
Этот ключ где-то используется?

2022-10-10 07:15 UTC, mrerberg commented on src/hoc/ThemeProvider.jsx
> +    const value = {theme: currentTheme, toggleTheme}
https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-no-constructed-context-values.md

2022-10-10 07:15 UTC, mrerberg commented on src/hook/useTheme.js
> +import { ThemeContext } from "../hoc/ThemeProvider"
Это не HOC, а просто провайдер

2022-10-11 17:07 UTC, Allgud commented on src/constants/constants.js
> +        title: 'light',
Используется только в одном месте.

2022-10-11 17:07 UTC, Allgud commented on src/hoc/ThemeProvider.jsx
> +    const value = {theme: currentTheme, toggleTheme}
Здесь не понял что требуется исправить

2022-10-12 07:14 UTC, mrerberg requested changes

2022-10-12 07:14 UTC, mrerberg commented on package.json
> +    "axios": "^1.1.2",
Зачем тебе сейчас эта либа?

2022-10-12 09:43 UTC, merged